import type { Metadata } from "next";
import "./globals.css";
import { UserContextProvider } from "@/context/usercontext";
import { CartProvider } from "@/context/cartcontext";
import { AdminOrdersProvider } from "@/context/adminOrdersContext";
import { FoodProvider } from "@/context/foodContext";
import { ErrorBoundary } from "@/components/ErrorBoundary";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorBoundary>
          <UserContextProvider>
            <CartProvider>
              <AdminOrdersProvider>
                <FoodProvider>
                  {children}
                  {/* <Toaster /> Uncomment if using a toaster notification */}
                </FoodProvider>
              </AdminOrdersProvider>
            </CartProvider>
          </UserContextProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
